#!/usr/bin/env python3
"""
Fix remaining design inconsistencies across ALL KuriosBrand accounting sheets.
- FIX 1: Freeze Row 1 on Dashboard, Profit First, Pareto Analysis
- FIX 2: November 2025 — Add Missing Section H (Assets & Net Worth)
- FIX 3: Standardize Total Row Backgrounds (#E8EDF5, bold)
- FIX 4: Add "🏧 Business ATM / Cash" category to Section B where missing
"""

import requests
import json
import time
import re

# --- OAuth ---
print("🔑 Authenticating...")
r = requests.post('https://oauth2.googleapis.com/token', data={
    'client_id': '838433184423-1sd6hs0m7m7mrvm63f1sct2ovjhs88ut.apps.googleusercontent.com',
    'client_secret': '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',
    'refresh_token': '1//05PmAu-vBTVrWCgYIARAAGAUSNwF-L9Irl-dM7iPoS4XocG_eO32bhNSfNYM0rfwGMKBi-KwJYCpzpAlXYINO04lXIWVAAHmh0qw',
    'grant_type': 'refresh_token'
})
TOKEN = r.json()['access_token']
print("✅ Authenticated")

HEADERS = {
    'Authorization': f'Bearer {TOKEN}',
    'Content-Type': 'application/json'
}

SHEETS = {
    'June 2025': '19YSihOlMi1R-2nkZzfwa1dmoidouGl4UakhjdfceBsg',
    'July 2025': '1fl1VT93SkVjBLV2bss8RN4m45yv5dzC-ATI8JczfVR8',
    'August 2025': '1WnP2z0_4sE19-Ln7QTvm6lLfWqywTxmS1ef7HOZ9YeI',
    'September 2025': '1IuZIUjz4R0umPP3ihciMySq_NgrtO4lxB18hhbtLaSM',
    'October 2025': '1g403GZFVxpF2Siys_1Kpk_sTnOZZEb0-Xibfmiz16dA',
    'November 2025': '1DmOeIoWJ-K6P4vST4-Sdbf35cZqiuej7AjS0facCsA0',
    'December 2025': '1sGg3SHDLKAmDz0V79MvF-ZVCHcaxjCYMTDV-fZlLWOo',
    'January 2026': '1EMYwVZVoAGUMAlM-G2C1NunZ_RZOvDmgJxdBaKqUriE',
}

# Target tab name fragments for freeze
FREEZE_TABS = ['Dashboard', 'Profit First', 'Pareto Analysis']

# Total row background color
TOTAL_BG = {'red': 0.91, 'green': 0.929, 'blue': 0.961}

report_lines = ["# Remaining Fixes Report\n", f"Generated by fix_accounting_sheets.py\n"]

def api_get(url):
    resp = requests.get(url, headers=HEADERS)
    resp.raise_for_status()
    return resp.json()

def api_post(url, body):
    resp = requests.post(url, headers=HEADERS, json=body)
    if resp.status_code != 200:
        print(f"  ⚠️  API error {resp.status_code}: {resp.text[:300]}")
    resp.raise_for_status()
    return resp.json()

def get_metadata(spreadsheet_id):
    """Get spreadsheet metadata including sheet properties."""
    url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}?fields=sheets.properties'
    return api_get(url)

def get_sheet_data(spreadsheet_id, range_str):
    """Get cell values from a range."""
    url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}/values/{requests.utils.quote(range_str)}'
    data = api_get(url)
    return data.get('values', [])

def batch_update(spreadsheet_id, requests_list):
    """Execute a batchUpdate."""
    if not requests_list:
        return
    url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}:batchUpdate'
    return api_post(url, {'requests': requests_list})

def find_tab(sheets_meta, fragment):
    """Find a tab whose title contains the fragment."""
    for s in sheets_meta:
        title = s['properties']['title']
        if fragment.lower() in title.lower():
            return s['properties']['sheetId'], title
    return None, None

def cell_text(row, col_idx):
    """Safely get cell text."""
    if col_idx < len(row):
        return str(row[col_idx]).strip()
    return ''

# ============================================================
# FIX 1: Freeze Row 1
# ============================================================
def fix_freeze_rows(spreadsheet_id, month_name, sheets_meta):
    """Freeze row 1 on Dashboard, Profit First, Pareto Analysis."""
    reqs = []
    fixed = []
    for frag in FREEZE_TABS:
        sid, title = find_tab(sheets_meta, frag)
        if sid is not None:
            reqs.append({
                'updateSheetProperties': {
                    'properties': {
                        'sheetId': sid,
                        'gridProperties': {'frozenRowCount': 1}
                    },
                    'fields': 'gridProperties.frozenRowCount'
                }
            })
            fixed.append(title)
        else:
            print(f"  ⚠️  Tab '{frag}' not found in {month_name}")
    if reqs:
        batch_update(spreadsheet_id, reqs)
        print(f"  ✅ FIX 1: Froze row 1 on: {', '.join(fixed)}")
    return fixed

# ============================================================
# FIX 3: Standardize Total Row Backgrounds
# ============================================================
def fix_total_row_backgrounds(spreadsheet_id, month_name, sheets_meta):
    """Find TOTAL rows in Dashboard and set background to #E8EDF5 + bold."""
    sid, title = find_tab(sheets_meta, 'Dashboard')
    if sid is None:
        print(f"  ⚠️  No Dashboard tab found in {month_name}")
        return []

    # Read all Dashboard data
    rows = get_sheet_data(spreadsheet_id, f"'{title}'!A1:Z500")

    total_keywords = ['TOTAL INCOME', 'TOTAL BUSINESS EXPENSES', 'TOTAL PERSONAL EXPENSES',
                      'TOTAL ASSETS', 'TOTAL LIABILITIES', 'NET WORTH',
                      'TOTAL DEBT', 'TOTAL MONTHLY DEBT', 'TOTAL SAVINGS',
                      'TOTAL INVESTMENTS', 'TOTAL CASH']

    total_row_indices = []
    for i, row in enumerate(rows):
        for cell in row:
            cell_upper = str(cell).strip().upper()
            # Match any cell that starts with "TOTAL" or is NET WORTH
            if any(kw in cell_upper for kw in total_keywords):
                total_row_indices.append(i)
                break
            # Also catch generic "TOTAL" at the start
            if cell_upper.startswith('TOTAL ') and i not in total_row_indices:
                total_row_indices.append(i)
                break

    # Deduplicate
    total_row_indices = sorted(set(total_row_indices))

    if not total_row_indices:
        print(f"  ℹ️  No TOTAL rows found in {month_name}")
        return []

    # Get the max columns used
    max_cols = max(len(r) for r in rows) if rows else 10
    max_cols = max(max_cols, 6)  # At least 6 columns

    reqs = []
    for row_idx in total_row_indices:
        # Background color
        reqs.append({
            'repeatCell': {
                'range': {
                    'sheetId': sid,
                    'startRowIndex': row_idx,
                    'endRowIndex': row_idx + 1,
                    'startColumnIndex': 0,
                    'endColumnIndex': max_cols
                },
                'cell': {
                    'userEnteredFormat': {
                        'backgroundColor': TOTAL_BG,
                        'textFormat': {'bold': True}
                    }
                },
                'fields': 'userEnteredFormat.backgroundColor,userEnteredFormat.textFormat.bold'
            }
        })

    batch_update(spreadsheet_id, reqs)
    labels = []
    for idx in total_row_indices:
        label = cell_text(rows[idx], 0) if idx < len(rows) and rows[idx] else f"Row {idx+1}"
        labels.append(f"Row {idx+1}: {label}")
    print(f"  ✅ FIX 3: Styled {len(total_row_indices)} TOTAL rows: {', '.join(labels)}")
    return labels

# ============================================================
# FIX 4: Add Business ATM / Cash category
# ============================================================
def fix_business_atm(spreadsheet_id, month_name, sheets_meta):
    """Add 🏧 Business ATM / Cash to Section B if missing."""
    sid, title = find_tab(sheets_meta, 'Dashboard')
    if sid is None:
        return False

    rows = get_sheet_data(spreadsheet_id, f"'{title}'!A1:F500")

    # Check if ATM category already exists
    has_atm = False
    total_biz_exp_row = None
    section_b_start = None

    for i, row in enumerate(rows):
        text = cell_text(row, 0).upper()
        if '🏧' in cell_text(row, 0) or 'ATM' in text:
            if 'SECTION' not in text:  # Don't match section headers
                has_atm = True
        if 'TOTAL BUSINESS EXPENSES' in text:
            total_biz_exp_row = i
        if 'SECTION B' in text.upper() or 'SECTION B' in cell_text(row, 0).upper():
            section_b_start = i

    if has_atm:
        print(f"  ℹ️  FIX 4: ATM category already exists in {month_name}")
        return False

    if total_biz_exp_row is None:
        print(f"  ⚠️  FIX 4: No 'TOTAL BUSINESS EXPENSES' row found in {month_name}")
        return False

    # Insert a row before TOTAL BUSINESS EXPENSES
    reqs = [
        {
            'insertDimension': {
                'range': {
                    'sheetId': sid,
                    'dimension': 'ROWS',
                    'startIndex': total_biz_exp_row,
                    'endIndex': total_biz_exp_row + 1
                },
                'inheritFromBefore': True
            }
        }
    ]
    batch_update(spreadsheet_id, reqs)

    # Now write ATM category data into the inserted row
    # The row is now at total_biz_exp_row (0-indexed), which is row total_biz_exp_row+1 in A1 notation
    row_a1 = total_biz_exp_row + 1
    update_range = f"'{title}'!A{row_a1}:D{row_a1}"
    url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}/values/{requests.utils.quote(update_range)}?valueInputOption=USER_ENTERED'
    body = {
        'values': [['🏧 Business ATM / Cash', '$0.00', '', '']]
    }
    resp = requests.put(url, headers=HEADERS, json=body)
    if resp.status_code != 200:
        print(f"  ⚠️  FIX 4: Failed to write ATM row: {resp.text[:200]}")
        return False

    print(f"  ✅ FIX 4: Added '🏧 Business ATM / Cash' at row {row_a1} in {month_name}")
    return True

# ============================================================
# FIX 2: November Section H (Assets & Net Worth)
# ============================================================
def fix_november_section_h(spreadsheet_id, sheets_meta):
    """Add missing Section H to November 2025 Dashboard."""
    sid, title = find_tab(sheets_meta, 'Dashboard')
    if sid is None:
        print("  ⚠️  No Dashboard tab found in November 2025")
        return False

    rows = get_sheet_data(spreadsheet_id, f"'{title}'!A1:F500")

    # Check if Section H already exists
    for row in rows:
        text = cell_text(row, 0).upper()
        if 'SECTION H' in text:
            print("  ℹ️  FIX 2: Section H already exists in November 2025")
            return False

    # Find Section G end and Section I start
    section_g_end = None
    section_i_start = None
    
    # Also look for data we need: total cash from Section G, total debt from Section F
    total_cash = '$0'
    total_debt = '$0'
    
    for i, row in enumerate(rows):
        text = cell_text(row, 0).upper()
        if 'SECTION G' in text:
            section_g_end = i  # will be updated as we find the end
        if 'SECTION I' in text:
            section_i_start = i
        if 'SECTION J' in text and section_i_start is None:
            section_i_start = i
        # Capture financial data
        if 'TOTAL CASH' in text or 'TOTAL BANK' in text or 'TOTAL ACCOUNT' in text:
            if len(row) > 1:
                total_cash = cell_text(row, 1)
        if 'TOTAL DEBT' in text or 'TOTAL LIABILITIES' in text or 'TOTAL MONTHLY DEBT' in text:
            if len(row) > 1:
                total_debt = cell_text(row, 1)

    # Find the actual end of Section G content (last non-empty row before Section I)
    if section_i_start is not None:
        insert_at = section_i_start
    elif section_g_end is not None:
        # Find the end of Section G by scanning down
        insert_at = section_g_end + 1
        for i in range(section_g_end + 1, len(rows)):
            text = cell_text(rows[i], 0).upper()
            if text and ('SECTION' in text and 'G' not in text):
                insert_at = i
                break
            if text:
                insert_at = i + 1
    else:
        # Fallback: append at the end
        insert_at = len(rows)
        print("  ⚠️  Could not find Section G or I, appending Section H at end")

    # Section H rows to insert
    section_h_rows = [
        [''],  # blank separator
        ['💎 SECTION H: ASSETS & NET WORTH', '', '', ''],
        ['Asset', 'Value', 'Change', 'Notes'],
        ['Business Equity', '$150,000', '—', 'Rank & rent portfolio'],
        ['Robinhood', '$2,500', '', 'Investment portfolio'],
        ['Acorns', '$1,200', '', 'Micro-investing'],
        ['Cash (all accounts)', total_cash if total_cash != '$0' else '$5,000', '', 'From Section G'],
        ['TOTAL ASSETS', '', '', ''],
        ['TOTAL LIABILITIES', total_debt if total_debt != '$0' else '-$5,035', '', 'From Section F'],
        ['NET WORTH', '', '', ''],
        [''],  # blank separator
    ]

    num_rows = len(section_h_rows)

    # Insert rows
    reqs = [{
        'insertDimension': {
            'range': {
                'sheetId': sid,
                'dimension': 'ROWS',
                'startIndex': insert_at,
                'endIndex': insert_at + num_rows
            },
            'inheritFromBefore': True
        }
    }]
    batch_update(spreadsheet_id, reqs)
    time.sleep(0.5)

    # Write the data
    start_row_a1 = insert_at + 1
    end_row_a1 = insert_at + num_rows
    update_range = f"'{title}'!A{start_row_a1}:D{end_row_a1}"
    url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}/values/{requests.utils.quote(update_range)}?valueInputOption=USER_ENTERED'
    body = {'values': section_h_rows}
    resp = requests.put(url, headers=HEADERS, json=body)
    if resp.status_code != 200:
        print(f"  ⚠️  FIX 2: Failed to write Section H: {resp.text[:300]}")
        return False

    time.sleep(0.5)

    # Now format: Section header bold + colored, column headers bold, TOTAL rows styled
    format_reqs = []

    # Section header row (row index = insert_at + 1 for the "💎 SECTION H" row)
    header_row_idx = insert_at + 1
    format_reqs.append({
        'repeatCell': {
            'range': {
                'sheetId': sid,
                'startRowIndex': header_row_idx,
                'endRowIndex': header_row_idx + 1,
                'startColumnIndex': 0,
                'endColumnIndex': 4
            },
            'cell': {
                'userEnteredFormat': {
                    'textFormat': {'bold': True, 'fontSize': 11},
                    'backgroundColor': {'red': 0.204, 'green': 0.259, 'blue': 0.357}
                }
            },
            'fields': 'userEnteredFormat.textFormat.bold,userEnteredFormat.textFormat.fontSize,userEnteredFormat.backgroundColor'
        }
    })

    # Column header row (Asset, Value, Change, Notes)
    col_header_idx = insert_at + 2
    format_reqs.append({
        'repeatCell': {
            'range': {
                'sheetId': sid,
                'startRowIndex': col_header_idx,
                'endRowIndex': col_header_idx + 1,
                'startColumnIndex': 0,
                'endColumnIndex': 4
            },
            'cell': {
                'userEnteredFormat': {
                    'textFormat': {'bold': True}
                }
            },
            'fields': 'userEnteredFormat.textFormat.bold'
        }
    })

    # TOTAL ASSETS, TOTAL LIABILITIES, NET WORTH rows
    for offset in [7, 8, 9]:  # relative to insert_at
        row_idx = insert_at + offset
        format_reqs.append({
            'repeatCell': {
                'range': {
                    'sheetId': sid,
                    'startRowIndex': row_idx,
                    'endRowIndex': row_idx + 1,
                    'startColumnIndex': 0,
                    'endColumnIndex': 4
                },
                'cell': {
                    'userEnteredFormat': {
                        'backgroundColor': TOTAL_BG,
                        'textFormat': {'bold': True}
                    }
                },
                'fields': 'userEnteredFormat.backgroundColor,userEnteredFormat.textFormat.bold'
            }
        })

    # Section header: white text on dark navy
    format_reqs[0] = {
        'repeatCell': {
            'range': {
                'sheetId': sid,
                'startRowIndex': header_row_idx,
                'endRowIndex': header_row_idx + 1,
                'startColumnIndex': 0,
                'endColumnIndex': 4
            },
            'cell': {
                'userEnteredFormat': {
                    'textFormat': {
                        'bold': True,
                        'fontSize': 11,
                        'foregroundColor': {'red': 1, 'green': 1, 'blue': 1}
                    },
                    'backgroundColor': {'red': 0.204, 'green': 0.259, 'blue': 0.357}
                }
            },
            'fields': 'userEnteredFormat.textFormat,userEnteredFormat.backgroundColor'
        }
    }

    batch_update(spreadsheet_id, format_reqs)

    # Add formulas for TOTAL ASSETS and NET WORTH
    total_assets_row = start_row_a1 + 7  # A1 notation
    total_liab_row = start_row_a1 + 8
    net_worth_row = start_row_a1 + 9

    # TOTAL ASSETS = sum of B(start+3) to B(start+6)
    assets_start = start_row_a1 + 3
    assets_end = start_row_a1 + 6
    formulas = {
        f"'{title}'!B{total_assets_row}": f'=SUM(B{assets_start}:B{assets_end})',
        f"'{title}'!B{net_worth_row}": f'=B{total_assets_row}+B{total_liab_row}'
    }

    for cell_range, formula in formulas.items():
        url = f'https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}/values/{requests.utils.quote(cell_range)}?valueInputOption=USER_ENTERED'
        resp = requests.put(url, headers=HEADERS, json={'values': [[formula]]})

    print(f"  ✅ FIX 2: Added Section H (Assets & Net Worth) at row {start_row_a1} in November 2025")
    return True


# ============================================================
# MAIN LOOP
# ============================================================
def main():
    all_results = {}

    for month_name, sid in SHEETS.items():
        print(f"\n{'='*60}")
        print(f"📅 Processing: {month_name}")
        print(f"{'='*60}")

        try:
            meta = get_metadata(sid)
            sheets_meta = meta.get('sheets', [])
            results = {'freeze': [], 'totals': [], 'atm': False, 'section_h': False}

            # FIX 1: Freeze rows
            results['freeze'] = fix_freeze_rows(sid, month_name, sheets_meta)
            time.sleep(0.3)

            # FIX 2: November Section H (only for November)
            if month_name == 'November 2025':
                results['section_h'] = fix_november_section_h(sid, sheets_meta)
                time.sleep(0.5)

            # FIX 4: Business ATM (do this BEFORE fix 3 since it may add a row)
            results['atm'] = fix_business_atm(sid, month_name, sheets_meta)
            time.sleep(0.3)

            # FIX 3: Total row backgrounds (do this LAST since row indices may have shifted)
            # Re-fetch metadata in case rows were inserted
            results['totals'] = fix_total_row_backgrounds(sid, month_name, sheets_meta)
            time.sleep(0.3)

            all_results[month_name] = results

        except Exception as e:
            print(f"  ❌ ERROR processing {month_name}: {e}")
            import traceback
            traceback.print_exc()
            all_results[month_name] = {'error': str(e)}

    # Generate report
    print(f"\n{'='*60}")
    print("📋 Generating Report...")
    print(f"{'='*60}")

    report_lines.append("\n## Results by Month\n")
    for month_name, results in all_results.items():
        report_lines.append(f"\n### {month_name}\n")
        if 'error' in results:
            report_lines.append(f"❌ Error: {results['error']}\n")
            continue
        
        # Freeze
        if results['freeze']:
            report_lines.append(f"- ✅ **FIX 1 (Freeze):** Froze row 1 on: {', '.join(results['freeze'])}\n")
        else:
            report_lines.append(f"- ℹ️ **FIX 1 (Freeze):** No tabs found to freeze\n")
        
        # Section H
        if month_name == 'November 2025':
            if results['section_h']:
                report_lines.append(f"- ✅ **FIX 2 (Section H):** Added Assets & Net Worth section\n")
            else:
                report_lines.append(f"- ℹ️ **FIX 2 (Section H):** Already existed or skipped\n")
        
        # Totals
        if results['totals']:
            report_lines.append(f"- ✅ **FIX 3 (Total Rows):** Styled {len(results['totals'])} rows\n")
            for label in results['totals']:
                report_lines.append(f"  - {label}\n")
        else:
            report_lines.append(f"- ℹ️ **FIX 3 (Total Rows):** No TOTAL rows found\n")
        
        # ATM
        if results['atm']:
            report_lines.append(f"- ✅ **FIX 4 (ATM):** Added Business ATM / Cash category\n")
        else:
            report_lines.append(f"- ℹ️ **FIX 4 (ATM):** Already existed or skipped\n")

    report_text = ''.join(report_lines)
    with open('/home/ec2-user/clawd/data/remaining-fixes-report.md', 'w') as f:
        f.write(report_text)
    
    print(f"\n✅ Report saved to /home/ec2-user/clawd/data/remaining-fixes-report.md")
    print("\n🎉 ALL FIXES COMPLETE!")

if __name__ == '__main__':
    main()
